// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmfhkhgnltaklqqrzrpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZmhraGdubHRha2xxcXJ6cnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODU0NTUsImV4cCI6MjA2MTY2MTQ1NX0.3f0q55TJ7RYvd1RkXNvYZgU3NKmQzqrRpWqp7UEf0LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);